import { runComponentTests } from "../../test/test-utils";
import "../../index";

describe("button", () => {
    runComponentTests({
        type: "a11y",
        baseClass: "s-btn",
        variants: ["danger", "muted", "primary"],
        modifiers: {
            primary: ["filled", "outlined"],
            secondary: [...["xs", "sm", "md"], ...["dropdown", "icon"]],
            global: ["is-loading"],
            standalone: [
                ...["link", "unset"],
                ...["facebook", "github", "google"],
            ],
        },
        attributes: {
            type: "button",
        },
        children: {
            default: "Ask question",
        },
        tag: "button",
        excludedTestids: [
            /primary-outlined/, // This combination is not supported
        ],
        // TODO: Most of those skipped tests should be fixed by the new Stacks 2.0 palette
        skippedTestids: [
            "s-btn-light",
            "s-btn-light-dropdown",
            "s-btn-light-dropdown-is-loading",
            "s-btn-light-icon",
            "s-btn-light-icon-is-loading",
            "s-btn-light-is-loading",
            "s-btn-light-link",
            "s-btn-light-muted-filled",
            "s-btn-light-muted-filled-dropdown",
            "s-btn-light-muted-filled-dropdown-is-loading",
            "s-btn-light-muted-filled-icon",
            "s-btn-light-muted-filled-icon-is-loading",
            "s-btn-light-muted-filled-is-loading",
            "s-btn-light-muted-filled-sm",
            "s-btn-light-muted-filled-sm-is-loading",
            "s-btn-light-muted-filled-xs",
            "s-btn-light-muted-filled-xs-is-loading",
            "s-btn-light-outlined",
            "s-btn-light-outlined-dropdown",
            "s-btn-light-outlined-dropdown-is-loading",
            "s-btn-light-outlined-icon",
            "s-btn-light-outlined-icon-is-loading",
            "s-btn-light-outlined-is-loading",
            "s-btn-light-outlined-sm",
            "s-btn-light-outlined-sm-is-loading",
            "s-btn-light-outlined-xs",
            "s-btn-light-outlined-xs-is-loading",
            "s-btn-light-sm",
            "s-btn-light-sm-is-loading",
            "s-btn-light-xs",
            "s-btn-light-xs-is-loading",
            "s-btn-dark",
            "s-btn-dark-danger",
            "s-btn-dark-danger-dropdown",
            "s-btn-dark-danger-dropdown-is-loading",
            "s-btn-dark-danger-icon",
            "s-btn-dark-danger-icon-is-loading",
            "s-btn-dark-danger-is-loading",
            "s-btn-dark-danger-md",
            "s-btn-dark-danger-md-is-loading",
            "s-btn-dark-danger-outlined",
            "s-btn-dark-danger-outlined-dropdown",
            "s-btn-dark-danger-outlined-dropdown-is-loading",
            "s-btn-dark-danger-outlined-icon",
            "s-btn-dark-danger-outlined-icon-is-loading",
            "s-btn-dark-danger-outlined-is-loading",
            "s-btn-dark-danger-outlined-md",
            "s-btn-dark-danger-outlined-md-is-loading",
            "s-btn-dark-danger-outlined-sm",
            "s-btn-dark-danger-outlined-sm-is-loading",
            "s-btn-dark-danger-outlined-xs",
            "s-btn-dark-danger-outlined-xs-is-loading",
            "s-btn-dark-danger-sm",
            "s-btn-dark-danger-sm-is-loading",
            "s-btn-dark-danger-xs",
            "s-btn-dark-danger-xs-is-loading",
            "s-btn-dark-dropdown",
            "s-btn-dark-dropdown-is-loading",
            "s-btn-dark-filled",
            "s-btn-dark-filled-dropdown",
            "s-btn-dark-filled-dropdown-is-loading",
            "s-btn-dark-filled-icon",
            "s-btn-dark-filled-icon-is-loading",
            "s-btn-dark-filled-is-loading",
            "s-btn-dark-filled-sm",
            "s-btn-dark-filled-sm-is-loading",
            "s-btn-dark-filled-xs",
            "s-btn-dark-filled-xs-is-loading",
            "s-btn-dark-google",
            "s-btn-dark-icon",
            "s-btn-dark-icon-is-loading",
            "s-btn-dark-is-loading",
            "s-btn-dark-link",
            "s-btn-dark-md",
            "s-btn-dark-md-is-loading",
            "s-btn-dark-muted",
            "s-btn-dark-muted-dropdown",
            "s-btn-dark-muted-dropdown-is-loading",
            "s-btn-dark-muted-filled",
            "s-btn-dark-muted-filled-dropdown",
            "s-btn-dark-muted-filled-dropdown-is-loading",
            "s-btn-dark-muted-filled-icon",
            "s-btn-dark-muted-filled-icon-is-loading",
            "s-btn-dark-muted-filled-is-loading",
            "s-btn-dark-muted-filled-sm",
            "s-btn-dark-muted-filled-sm-is-loading",
            "s-btn-dark-muted-filled-xs",
            "s-btn-dark-muted-filled-xs-is-loading",
            "s-btn-dark-muted-icon",
            "s-btn-dark-muted-icon-is-loading",
            "s-btn-dark-muted-is-loading",
            "s-btn-dark-muted-outlined",
            "s-btn-dark-muted-outlined-dropdown",
            "s-btn-dark-muted-outlined-dropdown-is-loading",
            "s-btn-dark-muted-outlined-icon",
            "s-btn-dark-muted-outlined-icon-is-loading",
            "s-btn-dark-muted-outlined-is-loading",
            "s-btn-dark-muted-outlined-sm",
            "s-btn-dark-muted-outlined-sm-is-loading",
            "s-btn-dark-muted-outlined-xs",
            "s-btn-dark-muted-outlined-xs-is-loading",
            "s-btn-dark-muted-sm",
            "s-btn-dark-muted-sm-is-loading",
            "s-btn-dark-muted-xs",
            "s-btn-dark-muted-xs-is-loading",
            "s-btn-dark-outlined",
            "s-btn-dark-outlined-dropdown",
            "s-btn-dark-outlined-dropdown-is-loading",
            "s-btn-dark-outlined-icon",
            "s-btn-dark-outlined-icon-is-loading",
            "s-btn-dark-outlined-is-loading",
            "s-btn-dark-outlined-md",
            "s-btn-dark-outlined-md-is-loading",
            "s-btn-dark-outlined-sm",
            "s-btn-dark-outlined-sm-is-loading",
            "s-btn-dark-outlined-xs",
            "s-btn-dark-outlined-xs-is-loading",
            "s-btn-dark-primary-filled",
            "s-btn-dark-primary-filled-dropdown",
            "s-btn-dark-primary-filled-dropdown-is-loading",
            "s-btn-dark-primary-filled-icon",
            "s-btn-dark-primary-filled-icon-is-loading",
            "s-btn-dark-primary-filled-is-loading",
            "s-btn-dark-primary-filled-sm",
            "s-btn-dark-primary-filled-sm-is-loading",
            "s-btn-dark-primary-filled-xs",
            "s-btn-dark-primary-filled-xs-is-loading",
            "s-btn-dark-sm",
            "s-btn-dark-sm-is-loading",
            "s-btn-dark-xs",
            "s-btn-dark-xs-is-loading",
        ],
    });
});
