version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      vite-major:
        patterns:
          - "vite"
          - "@sveltejs/vite-plugin-svelte"
        update-types:
          - "major"
