# Temporary to get stacks-svelte site to build ($SITE_ID below)
# We can remove this when we resolve stacks-docs with stacks-docs-next

[build]
  command = "npm run build -w packages/stacks-docs-next"
  publish = "packages/stacks-docs-next/build"
  ignore = "bash -c '[[ $BRANCH != alpha ]] || [[ $SITE_ID != 5d7b0a72-d965-4166-9286-0346fd1cdd1d ]]'"