[settings]
  ID = "34ae802e-fb42-4bab-8814-9fac9e119037"

[build]
  publish = "packages/stacks-docs/_site/"
  command = "npm run build -w packages/stacks-docs"
  # don't build deploy previews on PRs opened by dependabot
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  # IMPORTANT!: Git LFS settings can't be changed in the .toml file. You will need to set this environment
  # variable through the Netlify UI otherwise netlify won't be able to clone the repo due to all our images.
  # https://docs.netlify.com/build/configure-builds/environment-variables/#netlify-configuration-variables
  GIT_LFS_ENABLED = "true" # just here as a reminder

# Renamed pages
[[redirects]]
  from = "/product/base/grid"
  to = "/product/base/flex"

[[redirects]]
  from = "/product/base/pointer-events"
  to = "/product/base/interactivity"

[[redirects]]
  from = "/product/guidelines/releasing/"
  to = "https://github.com/StackExchange/Stacks#release-a-new-version-of-stacks"

[[redirects]]
  from = "/assets/img/logo-stacks@2x.png"
  to = "/assets/img/logos/so/logo-stacks@2x.png"

# Brand & copywriting → new site
[[redirects]]
  from = "/content"
  to = "https://stackoverflow.design/copy"
  status = 302

[[redirects]]
  from = "/content/guidelines/principles"
  to = "https://stackoverflow.design/copy"
  status = 302

[[redirects]]
  from = "/content/guidelines/voice-and-tone"
  to = "https://stackoverflow.design/copy/voice"
  status = 302

[[redirects]]
  from = "/content/guidelines/grammar-and-mechanics/"
  to = "https://stackoverflow.design/copy/styleguide#grammar-and-mechanics"
  status = 302

[[redirects]]
  from = "/content/examples/alt-text/"
  to = "https://stackoverflow.design/system/accessibility/alt"
  status = 302

[[redirects]]
  from = "/content/examples/error-messages/"
  to = "https://stackoverflow.design/copy/patterns/messages#error-messages"
  status = 302

[[redirects]]
  from = "/content/examples/preferences-settings/"
  to = "https://stackoverflow.design/copy/patterns/settings"
  status = 302

[[redirects]]
  from = "/content/examples/success-messages/"
  to = "https://stackoverflow.design/copy/patterns/messages#success-messages"
  status = 302

[[redirects]]
  from = "/brand"
  to = "https://stackoverflow.design/brand"
  status = 302

[[redirects]]
  from = "/brand/colors"
  to = "https://stackoverflow.design/brand/color"
  status = 302

[[redirects]]
  from = "/brand/copywriting/concepts"
  to = "https://stackoverflow.design/copy/styleguide#post-scores"
  status = 302

[[redirects]]
  from = "/brand/copywriting/naming"
  to = "https://stackoverflow.design/copy/naming"
  status = 302

[[redirects]]
  from = "/brand/data-visualization"
  to = "https://stackoverflow.design/brand"
  status = 302

[[redirects]]
  from = "/brand/logo"
  to = "https://stackoverflow.design/brand/logo"
  status = 302

[[redirects]]
  from = "/brand/typography"
  to = "https://stackoverflow.design/brand/typography"
  status = 302

[[redirects]]
  from = "/brand/principles"
  to = "https://stackoverflow.design/copy/voice"
  status = 302
