// Renders the spec-compliant llms.txt index at /llms.txt
// (see https://llmstxt.org). The full content dump lives at /llms-full.txt,
// generated by eleventy-plugin-llms-txt — see .eleventy.js.

const SECTIONS = [
  { tag: "base", heading: "Base utilities" },
  { tag: "components", heading: "Components" },
  { tag: "develop", heading: "Develop" },
  { tag: "foundation", heading: "Foundation" },
];

function pageLink(page, siteUrl) {
  const title = page.data.title;
  const description = (page.data.description || "")
    .replace(/<[^>]+>/g, "") // descriptions may contain inline HTML for the rendered page
    .replace(/\s+/g, " ")
    .trim();
  const suffix = description ? `: ${description}` : "";
  return `- [${title}](${siteUrl}${page.url})${suffix}`;
}

module.exports = class {
  data() {
    return {
      permalink: "/llms.txt",
      eleventyExcludeFromCollections: true,
    };
  }

  render({ collections, site }) {
    const sections = SECTIONS.map(({ tag, heading }) => {
      const pages = (collections[tag] || [])
        .slice()
        .sort((a, b) =>
          (a.data.title || "").localeCompare(b.data.title || "")
        );
      const lines = pages.map((p) => pageLink(p, site.url));
      return `## ${heading}\n\n${lines.join("\n")}`;
    });

    return `# ${site.title}

> ${site.description}

${sections.join("\n\n")}
`;
  }
};
