[settings]
  ID = "34ae802e-fb42-4bab-8814-9fac9e119037"

[build]
  base = "/" # Note: You'll need to set the "Package Directory" from the Netlify UI
  publish = "packages/stacks-docs/_site/"
  command = "npm run build -w packages/stacks-docs"
  # don't build deploy previews on PRs opened by dependabot
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  # IMPORTANT!: Git LFS settings can't be changed in the .toml file. You will need to set this environment 
  # variable through the Netlify UI otherwise netlify won't be able to clone the repo due to all our images.
  # https://docs.netlify.com/build/configure-builds/environment-variables/#netlify-configuration-variables
  GIT_LFS_ENABLED = "true" # just here as a reminder

# Build configuration for alpha branch (SvelteKit version)
[context.alpha.build]
  command = "npm run build -w packages/stacks-docs-next"
  publish = "packages/stacks-docs-next/build"

[[redirects]]
  from = "/favicon.ico"
  to = "/assets/img/favicons/favicon.ico"

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "/assets/img/favicons/apple-touch-icon.png"

[[redirects]]
  from = "/apple-touch-icon-precomposed.png"
  to = "/assets/img/favicons/apple-touch-icon-precomposed.png"

[[redirects]]
  from = "/product"
  to = "/product/develop/using-stacks/"

[[redirects]]
  from = "/email"
  to = "/email/guidelines/getting-started"

[[redirects]]
  from = "/product/guidelines"
  to = "/product/develop/using-stacks"

[[redirects]]
  from = "/email/guidelines"
  to = "/email/guidelines/getting-started"

[[redirects]]
  from = "/email/guidelines/best-practices"
  to = "/email/guidelines/design-best-practices"

[[redirects]]
  from = "/email/base"
  to = "/email/base/border-radius/"

[[redirects]]
  from = "/guidelines/using-stacks"
  to = "/product/develop/using-stacks"

[[redirects]]
  from = "/guidelines/responsiveness"
  to = "/product/develop/conditional-classes/#responsive"

[[redirects]]
  from = "/resources/icons"
  to = "/product/foundation/icons"

[[redirects]]
  from = "/base/borders"
  to = "/product/base/borders"

[[redirects]]
  from = "/base/box-shadow"
  to = "/product/base/box-shadow"

[[redirects]]
  from = "/base/box-sizing"
  to = "/product/base/box-sizing"

[[redirects]]
  from = "/base/colors"
  to = "/product/base/colors"

[[redirects]]
  from = "/base/cursors"
  to = "/product/base/cursors"

[[redirects]]
  from = "/base/display"
  to = "/product/base/display"

[[redirects]]
  from = "/base/floats"
  to = "/product/base/floats"

[[redirects]]
  from = "/base/grid"
  to = "/product/base/grid"

[[redirects]]
  from = "/product/base/grid"
  to = "/product/base/flex"

[[redirects]]
  from = "/base/opacity"
  to = "/product/base/opacity"

[[redirects]]
  from = "/base/overflow"
  to = "/product/base/overflow"

[[redirects]]
  from = "/base/pointer-events"
  to = "/product/base/pointer-events"

[[redirects]]
  from = "/base/position"
  to = "/product/base/position"

[[redirects]]
  from = "/base/spacing"
  to = "/product/base/spacing"

[[redirects]]
  from = "/base/typography"
  to = "/product/base/typography"

[[redirects]]
  from = "/base/vertical-alignment"
  to = "/product/base/vertical-alignment"

[[redirects]]
  from = "/base/width-height"
  to = "/product/base/width-height"

[[redirects]]
  from = "/base/z-index"
  to = "/product/base/z-index"

[[redirects]]
  from = "/components/avatars"
  to = "/product/components/avatars"

[[redirects]]
  from = "/components/badges"
  to = "/product/components/badges"

[[redirects]]
  from = "/components/banners"
  to = "/product/components/banners"

[[redirects]]
  from = "/components/buttons"
  to = "/product/components/buttons"

[[redirects]]
  from = "/components/button-groups"
  to = "/product/components/button-groups"

[[redirects]]
  from = "/components/cards"
  to = "/product/components/cards"

[[redirects]]
  from = "/components/checkbox"
  to = "/product/components/checkbox"

[[redirects]]
  from = "/components/inputs"
  to = "/product/components/inputs"

[[redirects]]
  from = "/components/labels"
  to = "/product/components/labels"

[[redirects]]
  from = "/components/links"
  to = "/product/components/links"

[[redirects]]
  from = "/components/modals"
  to = "/product/components/modals"

[[redirects]]
  from = "/components/notices"
  to = "/product/components/notices"

[[redirects]]
  from = "/components/progress-bars"
  to = "/product/components/progress-bars"

[[redirects]]
  from = "components/radio"
  to = "/product/components/radio"

[[redirects]]
  from = "/product/components/checkbox_radio"
  to = "/product/components/checkbox"

[[redirects]]
  from = "/components/select"
  to = "/product/components/select"

[[redirects]]
  from = "components/sidebar-widgets"
  to = "/product/components/sidebar-widgets"

[[redirects]]
  from = "/components/tables"
  to = "/product/components/tables"

[[redirects]]
  from = "/components/tags"
  to = "/product/components/tags"

[[redirects]]
  from = "/components/textarea"
  to = "/product/components/textarea"

[[redirects]]
  from = "/product/guidelines/responsiveness"
  to = "/product/develop/conditional-classes/#responsive"

[[redirects]]
  from = "/product/base/pointer-events"
  to = "/product/base/interactivity"

[[redirects]]
  from = "/assets/img/logo-stacks@2x.png"
  to = "/assets/img/logos/so/logo-stacks@2x.png"

[[redirects]]
  from = "/product/guidelines/releasing/"
  to = "https://github.com/StackExchange/Stacks#release-a-new-version-of-stacks"

[[redirects]]
  from = "/product/guidelines/releasing/"
  to = "https://github.com/StackExchange/Stacks#release-a-new-version-of-stacks"

[[redirects]]
  from = "/product/guidelines/using-stacks"
  to = "/product/develop/using-stacks"

[[redirects]]
  from = "/product/guidelines/building"
  to = "/product/develop/building"

[[redirects]]
  from = "/product/guidelines/conditional-classes"
  to = "/product/develop/conditional-classes"

[[redirects]]
  from = "/product/guidelines/javascript"
  to = "/product/develop/javascript"

[[redirects]]
  from = "/product/base/color-fundamentals"
  to = "/product/foundation/color-fundamentals"

[[redirects]]
  from = "/product/base/colors"
  to = "/product/foundation/colors"

[[redirects]]
  from = "/product/base/theming"
  to = "/product/foundation/theming"

[[redirects]]
  from = "/product/guidelines/theming"
  to = "/product/foundation/theming"

[[redirects]]
  from = "/product/resources/icons"
  to = "/product/foundation/icons"

[[redirects]]
  from = "/product/resources/spots"
  to = "/product/foundation/spots"

[[redirects]]
  from = "/product/base/typography"
  to = "/product/foundation/typography"

[[redirects]]
  from = "/product/base/width-height"
  to = "/product/base/width"

[[redirects]]
  from = "/product/base/spacing"
  to = "/product/base/margin"

# Brand & content migrated Feb 2026
# To-do: remove 'alpha' when launched 

[[redirects]]
  from = "/content"
  to = "https://alpha.stackoverflow.design/copy"
  status = 302

[[redirects]]
  from = "/content/guidelines/principles"
  to = "https://alpha.stackoverflow.design/copy"
  status = 302

[[redirects]]
  from = "/content/guidelines/voice-and-tone"
  to = "https://alpha.stackoverflow.design/copy/voice"
  status = 302

[[redirects]]
  from = "/content/guidelines/grammar-and-mechanics/"
  to = "https://alpha.stackoverflow.design/copy/styleguide#grammar-and-mechanics"
  status = 302

[[redirects]]
  from = "/content/examples/alt-text/"
  to = "https://alpha.stackoverflow.design/system/accessibility/alt"
  status = 302

[[redirects]]
  from = "/content/examples/error-messages/"
  to = "https://alpha.stackoverflow.design/copy/patterns/messages#error-messages"
  status = 302

[[redirects]]
  from = "/content/examples/preferences-settings/"
  to = "https://alpha.stackoverflow.design/copy/patterns/settings"
  status = 302

[[redirects]]
  from = "/content/examples/success-messages/"
  to = "https://alpha.stackoverflow.design/copy/patterns/messages#success-messages"
  status = 302

[[redirects]]
  from = "/brand"
  to = "https://alpha.stackoverflow.design/brand"
  status = 302

[[redirects]]
  from = "/brand/colors"
  to = "https://alpha.stackoverflow.design/brand/color"
  status = 302

[[redirects]]
  from = "/brand/copywriting/concepts"
  to = "https://alpha.stackoverflow.design/copy/styleguide#post-scores"
  status = 302

[[redirects]]
  from = "/brand/copywriting/naming"
  to = "https://alpha.stackoverflow.design/copy/naming"
  status = 302

[[redirects]]
  from = "/brand/data-visualization"
  to = "https://alpha.stackoverflow.design/brand"
  status = 302

[[redirects]]
  from = "/brand/logo"
  to = "https://alpha.stackoverflow.design/brand/logo"
  status = 302

[[redirects]]
  from = "/brand/typography"
  to = "https://alpha.stackoverflow.design/brand/typography"
  status = 302

[[redirects]]
  from = "/brand/principles"
  to = "https://alpha.stackoverflow.design/copy/voice"
  status = 302