[build]
  base = "/" # The Package Directory must be set to packages/stacks-docs in Netlify.
  # Netlify treats exit code 0 as "ignore this build" and non-zero as "build".
  ignore = "bash ./packages/stacks-docs/netlify-ignore.sh"
