name: Release

on:
    workflow_run:
        workflows:
            - CI
        branches:
            - develop
            - beta
        types:
            - completed

permissions: write-all

jobs:
    release:
        name: Release (latest or beta)
        if: |
            github.event.workflow_run.conclusion == 'success' &&
            (github.event.workflow_run.head_branch == 'develop' || github.event.workflow_run.head_branch == 'beta')
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout
              uses:
                  actions/checkout@v5
                  # make sure to checkout the commit that triggered the CI workflow
                  # (which is not necessarily the latest commit)
              with:
                  ref: ${{ github.event.workflow_run.head_commit.id }}

            - name: ⎔ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - name: 🏗 Install and Build
              run: |
                  npm ci
                  npm run build

            - name: 🚀 Create/Update Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  version: npm run version
                  publish: npm run release
                  title: "chore(new-release) (beta)"
                  commit: "chore(new-release) (beta)"
                  branch: ${{ github.event.workflow_run.head_branch == 'beta' && 'beta' || null }}
                  createGithubReleases: ${{ github.event.workflow_run.head_branch == 'develop' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.STACKS_TOOLING_GH_RW_PAT }}
                  NPM_TOKEN: ${{ secrets.NPM_API_KEY }}

# cancel the jobs if another workflow is kicked off for the same branch
concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
    cancel-in-progress: true
