name: Visual Regression Tests
run-name: Visual Regression Tests

on:
  workflow_call:
    inputs:
      should_run:
        description: 'Whether to run visual regression tests'
        type: boolean
        required: true

jobs:
  visual-regression-tests:
    name: Visual Regression Tests
    if: inputs.should_run == true
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: ⎔ Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: 🏗 Install Dependencies
        run: npm ci

      - name: 🔑 Setup SSH for private submodule
        run: |
          mkdir -p ~/.ssh
          echo -e "${SUBMODULE_SSH_KEY//_/\\n}" > ~/.ssh/id_rsa
          chmod og-rwx ~/.ssh/id_rsa
        env:
          SUBMODULE_SSH_KEY: ${{ secrets.SUBMODULE_SSH_KEY }}

      - name: ▶️ Visual Regression Tests
        run: npm run test:visual:ci -w packages/stacks-classic -- --config ./visual-runner/stacks-classic-runner-config/web-test-runner.config.ci.mjs
        env:
          BETTER_AUTH_SECRET: ${{ secrets.AUTH_SECRET || 'ci-build-placeholder-secret' }}

      - name: ⬆️ Upload Visual Regression Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: visual-regression-test-results
          path: packages/stacks-classic/screenshots
