name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  # this is to ensure the pipeline runs at least once a day
  # even when there is no active development in the codebase
  schedule:
    - cron: '0 6 * * 1-5' # every weekday at 6am UTC

jobs:
  build-and-test:
    name: ${{ matrix.command_description }}
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: true
      matrix:
        include:
        - command_description: Build
          command: npm run build
          needs_lfs: false
          needs_playwright: false
        - command_description: Lint
          command: npm run lint
          needs_lfs: false
          needs_playwright: false
        - command_description: Less Tests
          command: npm run test:less -w packages/stacks-classic
          needs_lfs: false
          needs_playwright: false
        - command_description: Unit Tests
          command: npm run test:unit -w packages/stacks-classic -- --config web-test-runner.config.ci.mjs
          needs_lfs: false
          needs_playwright: true
        - command_description: A11y Tests
          command: npm run test:a11y -w packages/stacks-classic -- --config web-test-runner.config.ci.mjs
          needs_lfs: false
          needs_playwright: true
        - command_description: Visual Regression Tests
          command: npm run test:visual:ci -w packages/stacks-classic -- --config ./visual-runner/stacks-classic-runner-config/web-test-runner.config.ci.mjs
          needs_lfs: true
          needs_playwright: false # we are using playwright docker image to run visual tests
    with:
      command: ${{ matrix.command }}
      command_description: ${{ matrix.command_description }}
      needs_playwright: ${{ matrix.needs_playwright }}
      needs_lfs: ${{ matrix.needs_lfs }}
