name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  # this is to ensure the pipeline runs at least once a day
  # even when there is no active development in the codebase
  schedule:
    - cron: '0 6 * * 1-5' # every weekday at 6am UTC

jobs:
  build-and-test:
    name: ${{ matrix.command_description }}
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: true
      matrix:
        include:
        - command_description: Build
          command: npm run build
          needs_lfs: false
          needs_playwright: false
        - command_description: Lint
          command: npm run lint
          needs_lfs: false
          needs_playwright: false
        - command_description: Tests
          command: npm run test:ci -workspaces -if-present
          needs_lfs: true
          needs_playwright: true
    with:
      command: ${{ matrix.command }}
      command_description: ${{ matrix.command_description }}
      needs_playwright: ${{ matrix.needs_playwright }}
      needs_lfs: ${{ matrix.needs_lfs }}
